# Tensor method

In [1]:
import torch
import torch.nn as nn

x = torch.tensor([[-1.0, 1.0]], requires_grad=True)

layer1 = nn.Linear(2, 2, False)
layer2 = nn.Linear(2, 2, False)
layer1.weight = nn.Parameter(torch.tensor([[1, 2], [0, 1]], dtype=torch.float32))
layer2.weight = nn.Parameter(torch.tensor([[2, 3], [0, 0]], dtype=torch.float32))

y1 = layer1(x)
y1.retain_grad()
y2 = layer2(y1)
y2.retain_grad()

In [2]:
grad = torch.autograd.grad(y2, y1, torch.ones_like(y2))[0]
print(grad)
print(y1.grad)

tensor([[2., 3.]])
tensor([[2., 3.]])


In [3]:
y1.grad = None
print(y1.grad)

None


In [4]:
grad = torch.autograd.grad(y1, x, grad)[0]
print(grad)
print(y1.grad)

tensor([[2., 7.]])
tensor([[2., 3.]])


# GradientEdge method

In [5]:
x = torch.tensor([[-1.0, 1.0]], requires_grad=True)

layer1 = nn.Linear(2, 2, False)
layer2 = nn.Linear(2, 2, False)
layer1.weight = nn.Parameter(torch.tensor([[1, 2], [0, 1]], dtype=torch.float32))
layer2.weight = nn.Parameter(torch.tensor([[2, 3], [0, 0]], dtype=torch.float32))

y1 = layer1(x)
y2 = layer2(y1)

In [6]:
y1g = torch.autograd.graph.get_gradient_edge(y1)
grad = torch.autograd.grad(y2, y1g, torch.ones_like(y2))[0]
print(grad)
print(y1g)

tensor([[2., 3.]])
GradientEdge(node=<MmBackward0 object at 0x7088c55ec3a0>, output_nr=0)


In [7]:
del y1
try:
    print(y1)
except NameError as e:
    print(e)

name 'y1' is not defined


In [8]:
grad = torch.autograd.grad(y1g, x, grad)[0]
print(grad)

tensor([[2., 7.]])
